import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';
import { createAuthByQR, createClient } from './kakaoforge-loader';

const DATA_DIR = join(homedir(), '.loco-termux');
const AUTH_PATH = join(DATA_DIR, 'kakaoforge-auth.json');
const STATE_PATH = join(DATA_DIR, 'loco-transport.json');
const COMMAND_STATE_PATH = join(DATA_DIR, 'command-state.json');
const DEVELOPER_ID_PATH = join(DATA_DIR, 'developer-id');

type AnyMap = Record<string, any>;
function loadJson(path: string): AnyMap { try { const v = JSON.parse(readFileSync(path, 'utf8')); return v && typeof v === 'object' ? v : {}; } catch { return {}; } }
function saveJson(path: string, value: unknown) { mkdirSync(DATA_DIR, { recursive: true }); writeFileSync(path, JSON.stringify(value, null, 2), 'utf8'); }
function saveState(patch: AnyMap) { const state = loadJson(STATE_PATH); saveJson(STATE_PATH, { ...state, ...patch, updatedAt: new Date().toISOString() }); }
function commandState() { return loadJson(COMMAND_STATE_PATH); }
function saveCommandState(state: AnyMap) { saveJson(COMMAND_STATE_PATH, state); }
function roomState(state: AnyMap, roomId: string): AnyMap { state.rooms ??= {}; state.rooms[roomId] ??= { registered: false, code: null, codeExpiresAt: 0, users: {}, admins: {}, readers: {}, messages: {} }; const r = state.rooms[roomId]; r.users ??= {}; r.admins ??= {}; r.readers ??= {}; r.messages ??= {}; return r; }
function developerId(client: any) { const env = String(process.env.LOCO_DEVELOPER_ID ?? '').trim(); if (env) return env; try { return readFileSync(DEVELOPER_ID_PATH, 'utf8').trim(); } catch { const id = String(client?.userId ?? ''); if (id) { mkdirSync(DATA_DIR, { recursive: true }); writeFileSync(DEVELOPER_ID_PATH, id, 'utf8'); } return id; } }
function isDeveloper(client: any, id: any) { return Boolean(id) && String(id) === developerId(client); }
function isBotManager(client: any) { const t = Number(client?.type); return t === 1 || t === 4; }
function registeredAdmin(room: AnyMap, id: any) { return Boolean(room?.admins?.[String(id)]); }
function senderIsRealManager(msg: any) { const s = msg?.sender ?? msg?.member ?? {}; const values = [s?.isManager, s?.isAdmin, s?.isHost, s?.isOwner, s?.isRoomAdmin, s?.isModerator, s?.role, s?.type, s?.memberType, s?.privilege, s?.authority, s?.status]; if (values.some(v => v === true)) return true; return values.some(v => ['ADMIN','MANAGER','HOST','OWNER','MODERATOR','LEADER','부방장','방장','관리자'].includes(String(v ?? '').toUpperCase())); }
function canModerate(client: any, msg: any, room: AnyMap, id: string) { return isDeveloper(client, id) || senderIsRealManager(msg) || registeredAdmin(room, id); }
function fmtTime(v: any) { const d = new Date(v); return Number.isNaN(d.getTime()) ? String(v ?? '') : d.toLocaleString('ko-KR', { hour12: false }); }
function chunk(lines: string[], max = 1800) { const out: string[] = []; let cur = ''; for (const line of lines) { if (cur && cur.length + line.length + 1 > max) { out.push(cur); cur = ''; } cur += `${cur ? '\n' : ''}${line}`; } if (cur) out.push(cur); return out; }
function helpText() { return ['╭────── LOCO-TERMUX 명령어 전체보기 ──────╮','│ 기본','│ !핑  !명령어  !봇정보','│','│ 관리자','│ !관리자 @유저  !관리자해제 @유저  !관리자목록','│ !입장로그  !퇴장로그  !입퇴장로그','│ !나간사람  !나간사람내보내기  !읽은사람  !채팅순위','│','│ 내보내기','│ !kick @유저  /  퇴장·입장 로그에 답장 + kick','│ !allkick','│','│ 방 관리','│ !봇등록  !방등록해제','│','│ 게임','│ !도박가입  !도박 <포인트>','╰──────────────────────────────────────╯'].join('\n'); }
function mentions(msg: any) { const values = [msg?.message?.mentions, msg?.message?.mention, msg?.mentions, msg?.mention, msg?.message?.meta?.mentions, msg?.message?.metadata?.mentions]; return values.flatMap(v => Array.isArray(v) ? v : v ? [v] : []); }
function mentionTarget(msg: any) { for (const m of mentions(msg)) { const id = m?.userId ?? m?.id ?? m?.memberId ?? m?.user?.id; const name = m?.name ?? m?.nickname ?? m?.user?.name ?? m?.user?.nickname; if (id != null) return { id: String(id), name: name == null ? undefined : String(name) }; } return null; }
function replyTarget(msg: any) { const r = msg?.replyTo ?? msg?.reply ?? msg?.message?.replyTo ?? msg?.message?.reply ?? msg?.message?.quote ?? msg?.quote ?? msg?.message?.metadata?.reply; if (!r) return null; const id = r?.userId ?? r?.memberId ?? r?.sender?.id ?? r?.author?.id; const name = r?.nickname ?? r?.name ?? r?.sender?.name ?? r?.author?.name; return { id: id == null ? '' : String(id), name: name == null ? '' : String(name) }; }
function appendMemberEvent(type: 'JOIN' | 'LEAVE' | 'KICK', event: any) { const state = loadJson(STATE_PATH); const history = Array.isArray(state.memberEvents) ? state.memberEvents : []; const roomId = String(event?.roomId ?? event?.chatId ?? event?.room?.id ?? event?.chat?.id ?? ''); const ids = Array.isArray(event?.member?.ids) ? event.member.ids : [event?.userId ?? event?.memberId ?? event?.sender?.id ?? event?.member?.id ?? '']; const names = Array.isArray(event?.member?.names) ? event.member.names : [event?.nickname ?? event?.name ?? event?.member?.name ?? event?.sender?.name ?? '알 수 없음']; const items = ids.map((id: any, i: number) => ({ type, at: new Date().toISOString(), roomId, roomName: String(event?.roomName ?? event?.room?.name ?? event?.chat?.name ?? ''), userId: String(id ?? ''), nickname: String(names[i] ?? names[0] ?? '알 수 없음') })).filter((x: any) => x.userId); history.push(...items); saveJson(STATE_PATH, { ...state, memberEvents: history.slice(-5000), lastMemberEvent: items.at(-1), updatedAt: new Date().toISOString() }); return items.at(-1); }
function eventHistory(type: string, roomId: string) { const s = loadJson(STATE_PATH); const e = Array.isArray(s.memberEvents) ? s.memberEvents : []; return e.filter((x: any) => (!type || x.type === type) && String(x.roomId) === String(roomId)); }
function departedRows(roomId: string) { const rows = eventHistory('LEAVE', roomId); const seen = new Set<string>(); return rows.filter((x: any) => { const id = String(x.userId); if (seen.has(id)) return false; seen.add(id); return true; }).reverse(); }
function readerSnapshot(value: any, depth = 0, seen = new Set<any>()): any { if (!value || typeof value !== 'object' || depth > 5 || seen.has(value)) return null; seen.add(value); for (const [key, raw] of Object.entries(value)) { const k = key.toLowerCase(); if (['readers','reader','readusers','readby','seenby','readmembers','readmember'].includes(k)) { const list = Array.isArray(raw) ? raw : raw && typeof raw === 'object' ? Object.values(raw) : []; const ids: string[] = []; const names: string[] = []; for (const x of list as any[]) { const id = x?.userId ?? x?.id ?? x?.memberId ?? x?.uid ?? (typeof x === 'string' || typeof x === 'number' ? x : undefined); const name = x?.name ?? x?.nickname ?? x?.nickName; if (id != null) ids.push(String(id)); if (name) names.push(String(name)); } if (ids.length || names.length) return { ids: [...new Set(ids)], names: [...new Set(names)], source: key }; } if (['readercount','readcount','seencount','seen_count','readers_count'].includes(k)) { const n = Number(raw); if (Number.isFinite(n)) return { ids: [], names: [], count: n, source: key }; } } for (const raw of Object.values(value)) { const r = readerSnapshot(raw, depth + 1, seen); if (r) return r; } return null; }
function recordMessage(room: any, msg: any, r: AnyMap) { const id = String(msg?.message?.id ?? msg?.message?.logId ?? msg?.id ?? ''); if (!id) return; const snap = readerSnapshot(msg) ?? readerSnapshot(msg?.message?.raw); r.messages[id] = { messageId: id, roomId: String(room?.id ?? ''), senderName: String(msg?.sender?.name ?? ''), readerIds: snap?.ids ?? [], readerNames: snap?.names ?? [], readerCount: snap?.count, available: Boolean(snap), at: new Date().toISOString() }; r.readers[id] = r.messages[id]; }
async function doKick(client: any, chat: any, roomId: string, targetId: string, targetName: string, send: (s: string) => Promise<any>) { if (!isBotManager(client)) { await send('❌ 봇이 Open Chat 방장/관리자가 아니어서 내보내기를 실행할 수 없습니다.'); return; } if (!targetId || targetId === String(client.userId)) { await send('❌ 내보낼 대상을 확인할 수 없습니다.'); return; } try { await chat.openChatKick(roomId, Number(targetId)); appendMemberEvent('KICK', { roomId, roomName: chat?.name, userId: targetId, nickname: targetName || '알 수 없음' }); await send(`✅ ${targetName ? `@${targetName}` : targetId} 내보내기 완료`); } catch (e) { await send(`❌ 내보내기 실패: ${e instanceof Error ? e.message : String(e)}`); } }
async function allMembers(client: any, chat: any, r: AnyMap) { for (const target of [chat, client]) { const fn = target?.getChatMembers ?? target?.getMembers ?? target?.openChatMembers; if (typeof fn !== 'function') continue; try { const result = await fn.call(target, String(chat?.id ?? '')); const raw = Array.isArray(result) ? result : Array.isArray(result?.members) ? result.members : Array.isArray(result?.users) ? result.users : []; const rows = raw.map((m: any) => ({ id: String(m?.id ?? m?.userId ?? m?.memberId ?? ''), name: m?.name ?? m?.nickname })).filter((m: any) => m.id); if (rows.length) return rows; } catch {} } return Object.entries(r.users ?? {}).map(([id, v]: [string, any]) => ({ id, name: v?.nickname })); }
async function announce(client: any, type: 'JOIN' | 'LEAVE', event: any) { const item = appendMemberEvent(type, event); if (!item?.roomId) return; const body = type === 'JOIN' ? `👋 ${item.nickname}님이 입장했습니다.` : `🚪 ${item.nickname}님이 나가셨습니다.\n${fmtTime(item.at)}`; try { const rooms = await client.getChatRooms(); const list = Array.isArray(rooms?.chats) ? rooms.chats : Array.isArray(rooms) ? rooms : []; const chat = list.find((x: any) => String(x?.id ?? x?.chatId ?? x?.c ?? '') === item.roomId); if (chat?.sendText) await chat.sendText(item.roomId, body); } catch (e) { console.error('[EVENT]', e); } }
async function handleCommand(client: any, chat: any, msg: any) { const text = String(msg?.message?.text ?? '').trim(); if (!text.startsWith('!') || String(msg?.sender?.id) === String(client?.userId)) return; const roomId = String(msg?.room?.id ?? chat?.id ?? ''); if (!roomId) return; const state = commandState(); const r = roomState(state, roomId); const userId = String(msg?.sender?.id ?? ''); const send = (s: string) => chat.sendText(roomId, s); const parts = text.split(/\s+/); const command = parts[0].toLowerCase(); const args = parts.slice(1); const admin = canModerate(client, msg, r, userId); r.users[userId] ??= { nickname: String(msg?.sender?.name ?? ''), messages: 0, joined: false, points: 0 }; r.users[userId].nickname = String(msg?.sender?.name ?? ''); try { switch (command) {
case '!명령어': await send(helpText()); break;
case '!핑': await send('🏓 pong!'); break;
case '!봇정보': await send(`🤖 LOCO-Termux\n방: ${String(msg?.room?.name ?? roomId)}\nOpen Chat: ${msg?.room?.isOpenChat === true ? 'YES' : 'NO'}\n등록 관리자: ${Object.keys(r.admins).length}명`); break;
case '!관리자': { if (!isBotManager(client) || !senderIsRealManager(msg)) { await send('❌ 실제 방장/부방장만 등록할 수 있습니다.'); break; } const t = mentionTarget(msg); if (!t) { await send('사용법: !관리자 @유저'); break; } r.admins[t.id] = { id: t.id, name: t.name ?? '' }; await send(`🛡️ ${t.name ? `@${t.name}` : t.id} 등록 완료`); break; }
case '!관리자해제': { if (!isBotManager(client) || !senderIsRealManager(msg)) { await send('❌ 실제 방장/부방장만 해제할 수 있습니다.'); break; } const t = mentionTarget(msg); if (!t) { await send('사용법: !관리자해제 @유저'); break; } delete r.admins[t.id]; await send(`✅ ${t.name ? `@${t.name}` : t.id} 해제 완료`); break; }
case '!관리자목록': if (!admin) { await send('🔒 권한이 없습니다.'); break; } await send(['🛡️ 등록 관리자 전체보기', ...Object.values(r.admins).map((x: any, i: number) => `${i + 1}. ${x.name || x.id}`)].join('\n') || '등록된 관리자가 없습니다.'); break;
case '!입장로그': case '!퇴장로그': case '!입퇴장로그': { if (!admin) { await send('🔒 권한이 없습니다.'); break; } const type = command === '!입장로그' ? 'JOIN' : command === '!퇴장로그' ? 'LEAVE' : ''; const rows = eventHistory(type, roomId).reverse(); const title = type === 'JOIN' ? '📥 전체 입장 로그' : type === 'LEAVE' ? '📤 전체 퇴장 로그' : '📜 전체 입퇴장 로그'; const lines = rows.map((x: any, i: number) => `${i + 1}. ${x.nickname} | ${fmtTime(x.at)} | ${x.userId}`); for (const c of chunk([title, ...lines])) await send(c); if (!lines.length) await send(`${title}\n기록이 없습니다.`); break; }
case '!나간사람': case '!나간사람내보내기': { if (!admin) { await send('🔒 권한이 없습니다.'); break; } const rows = departedRows(roomId); const lines = rows.map((x: any, i: number) => `${i + 1}. ${x.nickname} | ${fmtTime(x.at)} | ${x.userId}`); if (command === '!나간사람') { for (const c of chunk(['📤 전체 나간 사람', ...lines])) await send(c); break; } const p = join(DATA_DIR, `departed-${roomId}-${Date.now()}.txt`); writeFileSync(p, ['LOCO-TERMUX 전체 나간 사람', ...lines].join('\n'), 'utf8'); try { await chat.sendFile(roomId, p); } catch { for (const c of chunk(['📤 EXPORT', ...lines])) await send(c); } break; }
case '!읽은사람': { if (!admin) { await send('🔒 권한이 없습니다.'); break; } const latest = Object.values(r.readers).reverse()[0] as any; if (!latest) { await send('📖 읽음 데이터가 없습니다.'); break; } await send(`📖 최근 읽음 전체보기\n메시지: ${latest.messageId}\n읽은 사람: ${latest.readerNames?.join(', ') || latest.readerIds?.join(', ') || '식별 안 됨'}${latest.readerCount != null ? `\n읽음 수: ${latest.readerCount}` : ''}`); break; }
case '!채팅순위': { if (!admin) { await send('🔒 권한이 없습니다.'); break; } const rows = Object.values(r.users).sort((a: any, b: any) => Number(b.messages || 0) - Number(a.messages || 0)); await send(['🏆 채팅순위 전체보기', ...rows.map((x: any, i: number) => `${i + 1}. ${x.nickname || '알 수 없음'} — ${Number(x.messages || 0)}회`)].join('\n')); break; }
case '!봇등록': { if (!senderIsRealManager(msg)) { await send('❌ 실제 방장/부방장만 등록할 수 있습니다.'); break; } const now = Date.now(); if (!r.code || Number(r.codeExpiresAt) <= now) { r.code = String(Math.floor(10000000 + Math.random() * 90000000)); r.codeExpiresAt = now + 300000; } r.registered = true; await send(`🔐 방 등록코드: ${r.code}\n5분 이내 Termux 패널에서 등록하세요.`); break; }
case '!방등록해제': if (!senderIsRealManager(msg)) { await send('❌ 실제 방장/부방장만 해제할 수 있습니다.'); break; } r.registered = false; r.code = null; r.codeExpiresAt = 0; await send('✅ 현재 방 등록을 해제했습니다.'); break;
case '!kick': { if (!msg?.room?.isOpenChat || !admin) { await send('🔒 실제 부방장 또는 등록 관리자만 사용할 수 있습니다.'); break; } const reply = args.join(' ').trim().toLowerCase() === 'kick' ? replyTarget(msg) : null; const t = reply ?? mentionTarget(msg); if (!t?.id) { await send('사용법: !kick @유저 또는 퇴장/입장 로그에 답장하여 kick'); break; } await doKick(client, chat, roomId, t.id, t.name ?? '', send); break; }
case '!allkick': { if (!msg?.room?.isOpenChat || !admin) { await send('🔒 실제 부방장 또는 등록 관리자만 사용할 수 있습니다.'); break; } if (!isBotManager(client)) { await send('❌ 봇이 Open Chat 방장/관리자가 아닙니다.'); break; } const members = await allMembers(client, chat, r); let ok = 0; for (const t of members.filter((m: any) => m.id && m.id !== String(client.userId))) { try { await chat.openChatKick(roomId, Number(t.id)); appendMemberEvent('KICK', { roomId, roomName: chat?.name, userId: t.id, nickname: t.name }); ok++; } catch {} } await send(`🛡️ 전체 내보내기 완료\n성공 ${ok}명 / 대상 ${members.length}명`); break; }
case '!도박가입': if (r.users[userId].joined) { await send(`이미 가입됨: ${Number(r.users[userId].points || 0).toLocaleString()}P`); break; } r.users[userId].joined = true; r.users[userId].points = 1000; await send(`${r.users[userId].nickname}님 가입 완료! 1,000P`); break;
case '!도박': { if (!r.users[userId].joined) { await send('먼저 !도박가입'); break; } const n = Number(args[0]); const b = Number(r.users[userId].points || 0); if (!Number.isInteger(n) || n <= 0 || n > b) { await send(`사용법: !도박 <포인트>\n잔액: ${b.toLocaleString()}P`); break; } if (Math.random() < 0.5) { r.users[userId].points = b + n * 2; await send(`🎉 당첨! 잔액 ${r.users[userId].points.toLocaleString()}P`); } else { r.users[userId].points = b - n; await send(`💥 낙첨! 잔액 ${r.users[userId].points.toLocaleString()}P`); } break; }
default: return; }
saveCommandState(state); saveState({ lastCommand: { command, roomId, userId, nickname: String(msg?.sender?.name ?? ''), at: new Date().toISOString() } }); } catch (e) { console.error('[COMMAND]', e); try { await send(`❌ 명령 실행 실패: ${e instanceof Error ? e.message : String(e)}`); } catch {} } }

async function qrLogin() { console.log('\n[LOCO] KakaoForge QR 인증을 시작합니다.'); console.log('[LOCO] 본인 KakaoTalk 앱에서 직접 승인해야 합니다.'); return createAuthByQR({ authPath: AUTH_PATH }); }
async function main() { mkdirSync(DATA_DIR, { recursive: true }); if (!existsSync(AUTH_PATH)) await qrLogin(); const client: any = createClient({ authPath: AUTH_PATH, autoConnect: false, autoReconnect: true, debug: process.env.LOCO_DEBUG === '1' }); client.onReady(async () => { const dev = developerId(client); saveState({ connected: true, userId: String(client.userId), developerId: dev }); try { const result = await client.getChatRooms(); const rooms = Array.isArray(result?.chats) ? result.chats : Array.isArray(result) ? result : []; const normalized = rooms.map((x: any) => ({ id: String(x.id ?? x.chatId ?? x.c ?? ''), name: String(x.name ?? x.roomName ?? x.title ?? ''), isOpenChat: x.isOpenChat === true })).filter((x: any) => x.id); saveState({ rooms: normalized, roomCount: normalized.length }); } catch (e) { console.error('[LOCO] 방 목록 동기화 실패:', e instanceof Error ? e.message : String(e)); } }); client.onMessage(async (chat: any, msg: any) => { const room = msg?.room ?? chat; const state = commandState(); const r = roomState(state, String(room?.id ?? '')); const uid = String(msg?.sender?.id ?? ''); if (uid && uid !== String(client.userId)) { r.users[uid] ??= { nickname: String(msg?.sender?.name ?? ''), messages: 0, joined: false, points: 0 }; r.users[uid].nickname = String(msg?.sender?.name ?? ''); r.users[uid].messages = Number(r.users[uid].messages || 0) + 1; } recordMessage(room, msg, r); saveCommandState(state); await handleCommand(client, chat, msg); }); client.onJoin((event: any) => { void announce(client, 'JOIN', event); }); client.onLeave((event: any) => { void announce(client, 'LEAVE', event); }); client.onKick((event: any) => { appendMemberEvent('KICK', event); }); try { await client.connect(); saveState({ connected: true, startedAt: new Date().toISOString() }); } catch (error) { saveState({ connected: false, error: String(error) }); throw error; } await new Promise(() => {}); }
main().catch(error => { console.error('[FATAL]', error instanceof Error ? error.stack || error.message : String(error)); process.exitCode = 1; });
