import readline from 'node:readline/promises';
import { stdin as input, stdout as output } from 'node:process';
import { spawn, spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, openSync, readFileSync, unlinkSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';

const C={r:'\x1b[0m',c:'\x1b[36m',g:'\x1b[32m',y:'\x1b[33m',x:'\x1b[31m',d:'\x1b[2m',b:'\x1b[1m'};
const DATA=join(homedir(),'.loco-termux'); const AUTH=join(DATA,'kakaoforge-auth.json'); const PID=join(DATA,'openchat.pid'); const WANT=join(DATA,'openchat.desired'); const LOG=join(DATA,'openchat.log');
mkdirSync(DATA,{recursive:true,mode:0o700});
class Back extends Error{constructor(){super('BACK');this.name='Back';}}
const isBack=(e:unknown)=>e instanceof Back||(e instanceof Error&&e.message==='BACK');
async function ask(p:string){const rl=readline.createInterface({input,output});try{const v=(await rl.question(p)).trim();if(v==='00')throw new Back();return v;}finally{rl.close();}}
function clear(){process.stdout.write('\x1b[2J\x1b[H\x1b[3J');}
function head(t:string){clear();console.log(`${C.c}${C.b}╭────────────────────────────────────────────────────────────╮${C.r}`);console.log(`${C.c}${C.b}│${C.r} ${C.b}${t.padEnd(58).slice(0,58)}${C.r}${C.c}${C.b}│${C.r}`);console.log(`${C.c}${C.b}╰────────────────────────────────────────────────────────────╯${C.r}`);}
function py(args:string[],timeout=120000){const bins=[process.env.PYTHON_BIN,'python3','python'].filter(Boolean) as string[];let last:any=null;for(const b of bins){last=spawnSync(b,['방관리_cli.py',...args],{encoding:'utf8',timeout,maxBuffer:8*1024*1024,env:{...process.env,PYTHONIOENCODING:'utf-8',PYTHONUNBUFFERED:'1'}});if(!last.error)break;}return last;}
function out(r:any){if(r?.stdout?.trim())console.log(r.stdout.trim());if(r?.stderr?.trim())console.error(`${C.y}${r.stderr.trim()}${C.r}`);if(r?.error)console.error(`${C.x}${r.error.message}${C.r}`);if(r?.status&&r.status!==0)console.error(`${C.x}명령 실패 (exit ${r.status})${C.r}`);}
async function pause(){await ask(`\n${C.d}엔터=계속 · 00=메인 패널${C.r}`);}
function pid(){try{const n=Number(readFileSync(PID,'utf8').trim());return Number.isInteger(n)&&n>0?n:null;}catch{return null;}}
function alive(n:number|null){if(!n)return false;try{process.kill(n,0);return true;}catch{return false;}}
function want(){try{return readFileSync(WANT,'utf8').trim()==='1';}catch{return false;}}
function setWant(v:boolean){try{writeFileSync(WANT,v?'1':'0',{encoding:'utf8',mode:0o600});}catch(e){console.error(`${C.x}상태 저장 실패: ${e instanceof Error?e.message:String(e)}${C.r}`);}}
function authOk(){try{const v=JSON.parse(readFileSync(AUTH,'utf8'));return Boolean(v&&typeof v==='object'&&v.accessToken&&v.deviceUuid&&v.userId!==undefined);}catch{return false;}}
function status(){const p=pid();return alive(p)?'실행 중':want()?'비정상 종료':'정지됨';}
function start():boolean{if(!authOk()){console.log(`${C.y}⚠ 유효한 QR 로그인 세션이 필요합니다.${C.r}`);return false;}const p=pid();if(alive(p)){setWant(true);console.log(`${C.g}● 이미 실행 중 PID=${p}${C.r}`);return true;}try{unlinkSync(PID);}catch(e){if((e as NodeJS.ErrnoException).code!=='ENOENT')console.error(`${C.y}PID 정리 실패: ${e instanceof Error?e.message:String(e)}${C.r}`);}setWant(true);let fd:number;try{fd=openSync(LOG,'a',0o600);}catch(e){setWant(false);console.error(`${C.x}로그 파일을 열 수 없습니다: ${e instanceof Error?e.message:String(e)}${C.r}`);return false;}const ch=spawn(process.execPath,['dist/openchat-main.js'],{cwd:process.cwd(),detached:true,stdio:['ignore',fd,fd],env:{...process.env,PYTHONIOENCODING:'utf-8',PYTHONUNBUFFERED:'1'}});if(!ch.pid){setWant(false);console.error(`${C.x}런타임을 시작하지 못했습니다.${C.r}`);return false;}try{writeFileSync(PID,String(ch.pid),{encoding:'utf8',mode:0o600});}catch(e){setWant(false);try{process.kill(ch.pid,'SIGTERM');}catch{}console.error(`${C.x}PID 저장 실패: ${e instanceof Error?e.message:String(e)}${C.r}`);return false;}ch.unref();console.log(`${C.g}✓ 런타임 시작 PID=${ch.pid}${C.r}`);return true;}
async function stop():Promise<boolean>{setWant(false);const p=pid();if(!p||!alive(p)){try{unlinkSync(PID);}catch(e){if((e as NodeJS.ErrnoException).code!=='ENOENT')console.error(`${C.y}PID 정리 실패: ${e instanceof Error?e.message:String(e)}${C.r}`);}console.log(`${C.d}이미 정지 상태${C.r}`);return true;}try{process.kill(p,'SIGTERM');const deadline=Date.now()+3000;while(Date.now()<deadline&&alive(p))await new Promise(r=>setTimeout(r,100));if(alive(p)){process.kill(p,'SIGKILL');await new Promise(r=>setTimeout(r,150));}if(!alive(p)){try{unlinkSync(PID);}catch(e){if((e as NodeJS.ErrnoException).code!=='ENOENT')console.error(`${C.y}PID 정리 실패: ${e instanceof Error?e.message:String(e)}${C.r}`);}console.log(`${C.g}✓ 런타임 정지 완료${C.r}`);return true;}console.error(`${C.x}런타임 PID=${p}가 종료되지 않았습니다.${C.r}`);return false;}catch(e){console.error(`${C.x}정지 실패: ${e instanceof Error?e.message:String(e)}${C.r}`);return false;}}
let starting=false;
function watchdog(){const t=setInterval(()=>{if(starting||!want()||alive(pid()))return;starting=true;setTimeout(()=>{try{if(want()&&!alive(pid()))start();}finally{starting=false;}},1000).unref();},3000);t.unref();}
async function qr(){head('카카오톡 QR 로그인');console.log(`${C.g}QR 로그인${C.r}`);console.log(`${C.d}카카오톡에서 직접 승인하고 QR 세션이 저장될 때까지 이 화면을 유지하세요.${C.r}\n`);const npm=process.platform==='win32'?'npm.cmd':'npm';const r=spawnSync(npm,['run','login:qr'],{stdio:'inherit',env:{...process.env}});if(r.status===0&&authOk()){console.log(`${C.g}\n✓ QR 인증 저장 완료${C.r}`);start();}else console.log(`${C.x}\n✗ QR 로그인 실패${C.r}`);await pause();}
async function rooms(){head('방 관리 / 전체보기');out(py(['rooms']));await pause();}
async function add(){head('방 관리 / 등록');const v=await ask('방 ID: ');if(v)out(py(['add',v]));await pause();}
async function toggle(on:boolean){head(`방 관리 / ${on?'활성화':'비활성화'}`);const v=await ask('방 ID: ');if(v)out(py([on?'enable':'disable',v]));await pause();}
async function removeRoom(){head('방 관리 / 등록 해제');const v=await ask('방 ID: ');if(v&&((await ask(`'${v}' 방을 등록 해제할까요? y/N: `)).toLowerCase()==='y'))out(py(['remove',v]));await pause();}
async function members(){head('멤버 관리');const v=await ask('방 ID: ');if(v)out(py(['members',v]));await pause();}
async function readers(){head('읽은 사람 확인');const v=await ask('메시지 ID: ');if(v)out(py(['readers',v]));await pause();}
async function exportData(departed=false){head(departed?'나간 사람 내보내기':'데이터 내보내기');const room=await ask('방 ID(전체는 엔터): ');const fmt=(await ask('형식 json/csv [json]: ')).toLowerCase()||'json';if(!['json','csv'].includes(fmt)){console.log('json 또는 csv만 가능합니다.');await pause();return;}const def=departed?`loco-departed.${fmt}`:`loco-export.${fmt}`;const file=await ask(`파일명 [${def}]: `)||def;out(py([departed?'departed-export':'export',...(room?['--room-id',room]:[]),'--format',fmt,'--output',file]));await pause();}
async function log(){head('실행 로그');try{const a=readFileSync(LOG,'utf8').split(/\r?\n/).filter(Boolean);console.log(a.slice(-100).join('\n')||'(로그 없음)')}catch(e){console.log(`(로그 없음: ${e instanceof Error?e.message:String(e)})`);}await pause();}
async function statusPage(){head('시스템 상태');console.log(`인증: ${authOk()?C.g+'정상'+C.r:C.x+'없음'+C.r}`);console.log(`런타임: ${status()}`);console.log(`PID: ${pid()??'-'}`);console.log(`자동복구: ${want()?'켜짐':'꺼짐'}`);console.log(`데이터: ${DATA}`);console.log(`로그: ${LOG}`);await pause();}
function help(){head('명령어 목록');console.log(['!명령어  !핑  !봇정보  !봇상태','!관리자 @유저  !관리자해제 @유저  !관리자목록','!읽은사람  !채팅순위','!강퇴 @유저  !전체강퇴','!봇등록  !방등록해제','!입장로그  !퇴장로그  !입퇴장로그','!나간사람  !나간사람내보내기','!도박가입  !도박 <포인트>','!말하기 <문구>'].join('\n'));}
async function menu(){head('로코 텀럭스 / 통합 관리 패널');console.log(`인증 ${authOk()?C.g+'● QR 인증됨':C.x+'○ QR 로그인 필요'}${C.r}   런타임 ${status()}   PID ${pid()??'-'}`);console.log(`\n${C.c}[ 인증 관리 ]${C.r}`);console.log(' 1 QR 로그인');console.log(' 2 인증 상태');console.log(`\n${C.c}[ 방 관리 ]${C.r}`);console.log(' 3 방 전체보기   4 방 등록   5 방 활성화   6 방 비활성화   7 방 등록 해제');console.log(`\n${C.c}[ 데이터 관리 ]${C.r}`);console.log(' 8 멤버 목록   9 읽은 사람   10 전체 내보내기   11 나간 사람 내보내기');console.log(`\n${C.c}[ 실행 관리 ]${C.r}`);console.log(' 12 봇 시작   13 봇 정지   14 봇 재시작   15 실행 로그   16 명령어 목록');console.log(' 0 종료');console.log(`\n${C.d}※ 모든 입력창: 00=메인 패널 · 런타임은 패널과 분리 · 비정상 종료 자동복구${C.r}`);}
async function main(){watchdog();while(true){try{await menu();const c=await ask('\n로코 > ');switch(c){case'1':await qr();break;case'2':await statusPage();break;case'3':await rooms();break;case'4':await add();break;case'5':await toggle(true);break;case'6':await toggle(false);break;case'7':await removeRoom();break;case'8':await members();break;case'9':await readers();break;case'10':await exportData(false);break;case'11':await exportData(true);break;case'12':start();await pause();break;case'13':await stop();await pause();break;case'14':await stop();if(want()===false){setWant(true);start();}await pause();break;case'15':await log();break;case'16':help();await pause();break;case'0':setWant(false);process.exit(0);}}catch(e){if(isBack(e))continue;console.error(`${C.x}패널 오류: ${e instanceof Error?e.message:String(e)}${C.r}`);await new Promise(r=>setTimeout(r,500));}}}
void main();
